<?php

/**
 * Implementation of hook_node_export_features_default().
 */
function pika_variables_node_export_features_default() {
  $node_export = array(
  'code_string' => 'array(
  array(
    \'nid\' => \'402\',
    \'type\' => \'land_use_designation\',
    \'language\' => \'en\',
    \'uid\' => \'1\',
    \'status\' => \'1\',
    \'created\' => \'1340660370\',
    \'changed\' => \'1341526252\',
    \'comment\' => \'2\',
    \'promote\' => \'1\',
    \'moderate\' => \'0\',
    \'sticky\' => \'0\',
    \'tnid\' => \'0\',
    \'translate\' => \'0\',
    \'vid\' => \'451\',
    \'revision_uid\' => \'1\',
    \'title\' => \'Land use designation\',
    \'body\' => \'\',
    \'teaser\' => \'\',
    \'log\' => \'\',
    \'revision_timestamp\' => \'1341526252\',
    \'format\' => \'1\',
    \'name\' => \'admin\',
    \'picture\' => \'\',
    \'data\' => \'a:4:{s:13:"form_build_id";s:37:"form-71c3964fbeda4bebc48471387fc528be";s:21:"force_password_change";i:0;s:5:"block";a:2:{s:4:"user";a:1:{i:1;i:0;}s:5:"views";a:1:{s:16:"calendar-block_1";i:0;}}s:7:"contact";i:0;}\',
    \'path\' => \'land-use-designation\',
    \'_workflow\' => FALSE,
    \'print_display\' => 1,
    \'print_display_comment\' => 0,
    \'print_display_urllist\' => 1,
    \'last_comment_timestamp\' => \'1340660370\',
    \'last_comment_name\' => NULL,
    \'comment_count\' => \'0\',
    \'taxonomy\' => array(),
    \'files\' => array(),
    \'uuid\' => \'48f1721b-c6ee-11e1-a847-002590335e20\',
    \'revision_uuid\' => FALSE,
    \'menu\' => array(
      \'link_title\' => \'\',
      \'mlid\' => 0,
      \'plid\' => 0,
      \'menu_name\' => \'navigation\',
      \'weight\' => 0,
      \'options\' => array(),
      \'module\' => \'menu\',
      \'expanded\' => 0,
      \'hidden\' => 0,
      \'has_children\' => 0,
      \'customized\' => 0,
      \'parent_depth_limit\' => 8,
    ),
    \'export_display\' => \'$display = new ;
$display->layout = \\\'\\\';
$display->layout_settings = \\\'\\\';
$display->panel_settings = \\\'\\\';
$display->cache = \\\'\\\';
$display->title = \\\'\\\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \\\'0\\\';
\',
    \'#_export_node_encode_object\' => \'1\',
  ),
    array(
    \'nid\' => \'138\',
    \'type\' => \'page\',
    \'language\' => \'en\',
    \'uid\' => \'1\',
    \'status\' => \'1\',
    \'created\' => \'1321041515\',
    \'changed\' => \'1341526253\',
    \'comment\' => \'0\',
    \'promote\' => \'0\',
    \'moderate\' => \'0\',
    \'sticky\' => \'0\',
    \'tnid\' => \'0\',
    \'translate\' => \'0\',
    \'vid\' => \'138\',
    \'revision_uid\' => \'1\',
    \'title\' => \'Registry\',
    \'body\' => \'Settlement Land Registry System

The Settlement Land Registry System is a module that supports and facilitates the registration of settlement land parcels.

\',
    \'teaser\' => \'Settlement Land Registry System

The Settlement Land Registry System is a module that supports and facilitates the registration of settlement land parcels.

\',
    \'log\' => \'\',
    \'revision_timestamp\' => \'1341526253\',
    \'format\' => \'1\',
    \'name\' => \'admin\',
    \'picture\' => \'\',
    \'data\' => \'a:4:{s:13:"form_build_id";s:37:"form-71c3964fbeda4bebc48471387fc528be";s:21:"force_password_change";i:0;s:5:"block";a:2:{s:4:"user";a:1:{i:1;i:0;}s:5:"views";a:1:{s:16:"calendar-block_1";i:0;}}s:7:"contact";i:0;}\',
    \'path\' => \'registry\',
    \'_workflow\' => FALSE,
    \'print_display\' => 0,
    \'print_display_comment\' => 0,
    \'print_display_urllist\' => 0,
    \'last_comment_timestamp\' => \'1321041515\',
    \'last_comment_name\' => NULL,
    \'comment_count\' => \'0\',
    \'taxonomy\' => array(),
    \'files\' => array(),
    \'uuid\' => \'49377995-c6ee-11e1-a847-002590335e20\',
    \'revision_uuid\' => FALSE,
    \'menu\' => array(
      \'link_title\' => \'\',
      \'mlid\' => 0,
      \'plid\' => 0,
      \'menu_name\' => \'navigation\',
      \'weight\' => 0,
      \'options\' => array(),
      \'module\' => \'menu\',
      \'expanded\' => 0,
      \'hidden\' => 0,
      \'has_children\' => 0,
      \'customized\' => 0,
      \'parent_depth_limit\' => 8,
    ),
    \'export_display\' => \'$display = new ;
$display->layout = \\\'\\\';
$display->layout_settings = \\\'\\\';
$display->panel_settings = \\\'\\\';
$display->cache = \\\'\\\';
$display->title = \\\'\\\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \\\'0\\\';
\',
    \'#_export_node_encode_object\' => \'1\',
  ),
    array(
    \'nid\' => \'403\',
    \'type\' => \'fnsettlementlands\',
    \'language\' => \'en\',
    \'uid\' => \'1\',
    \'status\' => \'1\',
    \'created\' => \'1340662245\',
    \'changed\' => \'1341525624\',
    \'comment\' => \'2\',
    \'promote\' => \'1\',
    \'moderate\' => \'0\',
    \'sticky\' => \'0\',
    \'tnid\' => \'0\',
    \'translate\' => \'0\',
    \'vid\' => \'452\',
    \'revision_uid\' => \'1\',
    \'title\' => \'Kluane First Nation Settlement Lands\',
    \'body\' => \'\',
    \'teaser\' => \'\',
    \'log\' => \'\',
    \'revision_timestamp\' => \'1341525624\',
    \'format\' => \'0\',
    \'name\' => \'admin\',
    \'picture\' => \'\',
    \'data\' => \'a:4:{s:13:"form_build_id";s:37:"form-71c3964fbeda4bebc48471387fc528be";s:21:"force_password_change";i:0;s:5:"block";a:2:{s:4:"user";a:1:{i:1;i:0;}s:5:"views";a:1:{s:16:"calendar-block_1";i:0;}}s:7:"contact";i:0;}\',
    \'path\' => \'kluane-first-nation-settlement-lands\',
    \'_workflow\' => FALSE,
    \'field_fnsl_firstnation\' => array(
      \'0\' => array(
        \'value\' => \'Kluane\',
      ),
    ),
    \'field_fnsl_kml\' => array(
      \'0\' => array(
        \'fid\' => \'392\',
        \'uid\' => \'1\',
        \'filename\' => \'KFN_SL_incl_unsurveyed_Project_WGS_With_URL.kml\',
        \'filepath\' => \'sites/11pc.v4730969223.v180p.nyc.host8.biz/files/useruploaded/fnsettlementlands/403/KFN_SL_incl_unsurveyed_Project_WGS_With_URL.kml\',
        \'filemime\' => \'application/vnd.google-earth.kml+xml\',
        \'filesize\' => \'1033642\',
        \'status\' => \'1\',
        \'timestamp\' => \'1340816106\',
        \'origname\' => \'KFN_SL_incl_unsurveyed_Project_WGS_With_URL.kml\',
        \'list\' => \'1\',
        \'data\' => array(
          \'fid\' => \'392\',
          \'width\' => 0,
          \'height\' => 0,
          \'duration\' => 0,
          \'audio_format\' => \'\',
          \'audio_sample_rate\' => 0,
          \'audio_channel_mode\' => \'\',
          \'audio_bitrate\' => 0,
          \'audio_bitrate_mode\' => \'\',
          \'tags\' => array(),
        ),
      ),
    ),
    \'print_display\' => 1,
    \'print_display_comment\' => 0,
    \'print_display_urllist\' => 1,
    \'last_comment_timestamp\' => \'1340662245\',
    \'last_comment_name\' => NULL,
    \'comment_count\' => \'0\',
    \'taxonomy\' => array(),
    \'files\' => array(),
    \'uuid\' => \'d29e3d2c-c6ec-11e1-a847-002590335e20\',
    \'revision_uuid\' => FALSE,
    \'menu\' => array(
      \'link_title\' => \'\',
      \'mlid\' => 0,
      \'plid\' => 0,
      \'menu_name\' => \'navigation\',
      \'weight\' => 0,
      \'options\' => array(),
      \'module\' => \'menu\',
      \'expanded\' => 0,
      \'hidden\' => 0,
      \'has_children\' => 0,
      \'customized\' => 0,
      \'parent_depth_limit\' => 8,
    ),
    \'export_display\' => \'$display = new ;
$display->layout = \\\'\\\';
$display->layout_settings = \\\'\\\';
$display->panel_settings = \\\'\\\';
$display->cache = \\\'\\\';
$display->title = \\\'\\\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \\\'0\\\';
\',
    \'#_export_node_encode_object\' => \'1\',
  ),
    array(
    \'nid\' => \'330\',
    \'type\' => \'home_page_map\',
    \'language\' => \'en\',
    \'uid\' => \'1\',
    \'status\' => \'1\',
    \'created\' => \'1339600323\',
    \'changed\' => \'1341532997\',
    \'comment\' => \'0\',
    \'promote\' => \'1\',
    \'moderate\' => \'0\',
    \'sticky\' => \'0\',
    \'tnid\' => \'0\',
    \'translate\' => \'0\',
    \'vid\' => \'354\',
    \'revision_uid\' => \'1\',
    \'title\' => \'Welcome to PIKA - Integrated Knowledge Application\',
    \'body\' => \'\',
    \'teaser\' => \'\',
    \'log\' => \'\',
    \'revision_timestamp\' => \'1341532997\',
    \'format\' => \'1\',
    \'name\' => \'admin\',
    \'picture\' => \'\',
    \'data\' => \'a:4:{s:13:"form_build_id";s:37:"form-71c3964fbeda4bebc48471387fc528be";s:21:"force_password_change";i:0;s:5:"block";a:2:{s:4:"user";a:1:{i:1;i:0;}s:5:"views";a:1:{s:16:"calendar-block_1";i:0;}}s:7:"contact";i:0;}\',
    \'path\' => \'welcome-pika-integrated-knowledge-application\',
    \'_workflow\' => FALSE,
    \'field_home_quartzclaim\' => array(
      \'0\' => array(
        \'openlayers_wkt\' => NULL,
      ),
    ),
    \'field_home_reservations\' => array(
      \'0\' => array(
        \'openlayers_wkt\' => NULL,
      ),
    ),
    \'field_home_settlementlands\' => array(
      \'0\' => array(
        \'openlayers_wkt\' => NULL,
      ),
    ),
    \'print_display\' => 1,
    \'print_display_comment\' => 0,
    \'print_display_urllist\' => 1,
    \'last_comment_timestamp\' => \'1339600323\',
    \'last_comment_name\' => NULL,
    \'comment_count\' => \'0\',
    \'taxonomy\' => array(),
    \'files\' => array(),
    \'uuid\' => \'d2c5c356-c6ec-11e1-a847-002590335e20\',
    \'revision_uuid\' => FALSE,
    \'menu\' => array(
      \'link_title\' => \'Home\',
      \'mlid\' => 0,
      \'plid\' => \'0\',
      \'menu_name\' => \'primary-links\',
      \'weight\' => \'-50\',
      \'options\' => array(),
      \'module\' => \'menu\',
      \'expanded\' => \'0\',
      \'hidden\' => \'0\',
      \'has_children\' => \'0\',
      \'customized\' => 0,
      \'parent_depth_limit\' => 8,
    ),
    \'export_display\' => \'$display = new ;
$display->layout = \\\'\\\';
$display->layout_settings = \\\'\\\';
$display->panel_settings = \\\'\\\';
$display->cache = \\\'\\\';
$display->title = \\\'\\\';
$display->content = array();
$display->panels = array();
$display->hide_title = PANELS_TITLE_FIXED;
$display->title_pane = \\\'0\\\';
\',
    \'#_export_node_encode_object\' => \'1\',
  ),
)',
);
  return $node_export;
}
